USE [Mall]
GO

/****** Object:  Table [dbo].[ProductCDNUrl]    Script Date: 3/13/2022 10:20:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ProductCDNUrl](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ean] [nvarchar](20) NOT NULL,
	[cdnUrl] [nvarchar](100) NOT NULL,
	[latestUpdated] [nvarchar](10) NULL,
 CONSTRAINT [PK_ProductCDNUrl] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

